Repository DguFarmSystem/4th-security-S2-FE, pull requests merged in 2025-05, with the labels that each got.

#2 [Chore] 프로젝트 모듈 설치 및 세팅
  package.json
  pnpm-lock.yaml
  src/App.tsx
  src/Router.tsx
  src/apis/instance.ts
  src/apis/sign_in/dto/.gitkeep
  src/apis/sign_in/index.ts
  src/apis/sign_in/mutations/.gitkeep
  src/apis/sign_in/queries/.gitkeep
  src/apis/sign_in/queries/queryKey.ts
  src/apis/sign_in/sign_up.api.ts
  src/assets/fonts/Pretendard-Regular.woff2
  src/assets/icons/.gitkeep
  src/components/common/button/Button.tsx
  src/components/common/button/ButtonLoader.tsx
  src/components/common/input/Input.tsx
  src/components/layout/Layout.tsx
  src/components/status/error/APIErrorBoundary.tsx
  src/components/status/error/APIErrorFallback.tsx
  src/components/status/error/ErrorPage.tsx
  src/components/status/error/ErrorPageLayout.tsx
  src/components/status/error/SomethingWentWrongPage.tsx
  src/components/status/error/UnknownErrorBoundary.tsx
  src/components/status/error/UnknownErrorFallback.tsx
  src/components/status/loading/Loader.tsx
  src/constants/api.ts
  src/constants/path.ts
  src/hooks/.gitkeep
  src/index.css
  src/main.tsx
  src/pages/RootPage.tsx
  src/pages/_Layout.tsx
  src/routes/AppRouter.tsx
  src/routes/PrivateRoute.tsx
  src/routes/PublicRoute.tsx
  src/styles/baseStyle.css
  src/styles/designSystem.css
  src/styles/fontStyle.css
  src/styles/index.css
  src/utils/customTwMerge.ts
  src/utils/fetchApiData.ts
  src/utils/getApiErrorInfo.ts
  src/utils/mergeClassNames.ts
  src/vite-env.d.ts
  vite.config.ts
Labels: 🛠️ chore

#4 chore: ci/cd 워크플로우 제작
  .github/workflows/ci.yml
  .github/workflows/deploy.yml
  build.sh
  tsconfig.app.json
Labels: 🛠️ chore

#6 User Role에 따른 화면 분기 처리
  package.json
  pnpm-lock.yaml
  src/assets/icons/IconCertified.svg
  src/assets/icons/IconComment.svg
  src/assets/icons/IconKakaoLogin.svg
  src/assets/icons/IconMainLogo.svg
  src/assets/icons/IconMenuGroupAuth.svg
  src/assets/icons/IconMenuHeart.svg
  src/assets/icons/IconMenuHome.svg
  src/assets/icons/IconMenuPen.svg
  src/assets/icons/IconMenuProfile.svg
  src/assets/icons/IconRightChevron.svg
  src/assets/icons/IconSubLogo.svg
  src/components/common/button/Button.tsx
  src/components/landing/LandingPageLayout.tsx
  src/components/landing/SplashGate.tsx
  src/components/landing/WelcomePage.tsx
  src/components/layout/Layout.tsx
  src/components/status/error/APIErrorFallback.tsx
  src/constants/path.ts
  src/hooks/.gitkeep
  src/hooks/useOauth.ts
  src/hooks/useUserRole.tsx
  src/pages/RootPage.tsx
  src/pages/_Layout.tsx
  src/pages/auth/dgu_auth/index.tsx
  src/pages/auth/oauth/KakaoLogin.tsx
  src/pages/auth/sign_in/index.tsx
  src/pages/landing/index.tsx
  src/routes/AppRouter.tsx
  src/routes/PrivateRoute.tsx
  src/routes/PublicRoute.tsx
  src/stores/authStore.ts
  src/styles/baseStyle.css
  src/styles/designSystem.css
  src/types/oauth/oauthType.ts
  src/utils/cookie.ts
Labels: ✨ feature, 🛠️ chore

#8 [Feat] 로그인 및 학교 인증 화면 개발
  src/assets/icons/IconBack.svg
  src/components/auth/dgu_auth/DGUAuthLayout.tsx
  src/components/auth/dgu_auth/JoinForm.tsx
  src/components/auth/dgu_auth/JoinFormPage.tsx
  src/components/auth/dgu_auth/JoinPromptPage.tsx
  src/components/common/button/Button.tsx
  src/components/common/input/Input.tsx
  src/components/landing/SplashGate.tsx
  src/components/landing/WelcomePage.tsx
  src/components/layout/Layout.tsx
  src/hooks/useFunnel.tsx
  src/pages/auth/dgu_auth/index.tsx
  src/styles/baseStyle.css
  src/styles/designSystem.css
  src/utils/formatTime.ts
Labels: ✨ feature
